config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index"
  post "users/login", to: "users#login"
  resources :todos # creates seven different resources
  resources :users # creates seven different resources

  get "/signin" => "sessions#new", as: "new_sessions"
  post "/signin" => "sessions#create", as: "sessions"
  delete "/signout" => "sessions#destroy", as: "destroy_session"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo <ActiveRecord::Base

  validates :todo_text, presence: true
  validates :todo_text, length: {minimum: 2}
  validates :due_date, presence: true

  belongs_to :user
    # Below conditions need to met while writing above code
    # Table called "users"
    # todos table will contain "user_id"

  def to_pleasent_string
    is_completed = completed ? "[X]" : "[ ]"
    "#{id}. #{is_completed} #{todo_text}, #{due_date}"
  end

  def self.overdue
    where("due_date < ? and (not completed)", Date.today)
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.duelater
    all.where("due_date > ?", Date.today)
  end

  def self.duetoday
    all.where("due_date = ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end

end

app/models/user.rb
require 'active_record'

class User < ApplicationRecord

  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password
  has_many :todos

  def to_pleasent_string
    "#{id}. #{first_name}, #{email}, #{password}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :ensure_user_logged_in

  def new
    render "sessions/new"
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to todos_path
    else
      flash[:error] = "Your login attempt was invalid. Please retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user =nil
    redirect_to "/"
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :verify_authenticity_token

  ## To list todos of all users using http://localhost:3000/todos
  # def index
  #   #render plain: Todo.order(:due_date).map{ |todo| todo.to_pleasent_string }.join("\n")
  # end

  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]

    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id
    )

    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end

  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed;
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :ensure_user_logged_in

  # # Use below code to list all users using  http://localhost:3000/users/index
  # def index
  #   render plain: User.all.map{ |user| user.to_pleasent_string }.join("\n")
  # end

  # # Use below to list user details given "id" using  http://localhost:3000/users/id
  # def show
  #   id = params[:id]
  #   user = User.find(id)
  #   render plain: user.to_pleasent_string
  # end

  def new
    render "/user/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password]
    )

    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to todos_path
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="Home__contents">

  <p class="Home__title"> Welcome to the Todo Home Page </p>

  <p class="Home__authenticate">
    If you are a new user, <%= link_to "sign up here", new_user_path %>
  </p>

  <p class="Home__authenticate">
    If you are an existing user, <%= link_to "sign-in here", new_sessions_path %>
  </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
        <p class="User__Header" >
          Welcome <%= @current_user.first_name %>
          <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
        </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash__error" >
        <%= flash[:error] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">

  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle__Text">
      <%= section_title %>
    </p>
    <p class="TodoSectionTitle__RemainingCount">
      <%= todos.completed.count %>/<%= todos.count %>
    </p>
  </div>

  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem__Container">

          <%= form_with(url:"/todos/#{todo.id}", method: "put") do %>
            <%# Evaluators please note, comments are kept intentinally%>
            <%# <input
              class="TodoItem__Checkbox"
              name="completed"
              type="checkbox" <%= todo.completed ? "checked" : "" %>
            <%#   onclick="this.form.submit()"
            > %>
            <%# <input type="submit" value = "Update"> %>

            <%= check_box_tag 'completed', 'yes', todo.completed,
              class: 'TodoItem__Checkbox',
              onclick: 'this.form.submit()'
            %>
          <% end %>

          <% if todo.completed %>
            <p class="TodoItem__StrikedText" >
              <%= todo.todo_text %>
            </p>
          <% else%>
            <p class="TodoItem__Text" >
              <%= todo.todo_text %>
            </p>
          <% end %>

          <% if show_duedate %>
            <p class="TodoItem__Duemonth">
              <%= todo.due_date.to_s(:short) %>
            </p>
          <% end %>

          <a class="TodoItem__DeleteButton" href="javascript:void(0)">
            <%= form_with(url:"/todos/#{todo.id}", method: "delete") do %>
              <%# <input type='image' src="/assets/bin.ico" width =10px> %>
              <%= image_submit_tag("bin.ico", width: "20px") %>
            <% end %>
          </a>

        </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
  <main class="TodoPageMain">
    <article>
      <h1 class="TodoPage__Title"> Todo list </h1>

      <%# Evaluators please note: Below Comment is retained intentionaly %>
      <%# <form class="AddTodo" action="/todos" method="POST"> %>
          <%# <input class="AddTodo__Text" type="text" placeholder="Whats Next?" name="todo_text"> %>
          <%# <input class="AddTodo__Date" type="date" name="due_date"> %>
          <%# <input class="AddTodo__Button" type="submit" placeholder="Add" value="Add"> %>
      <%# </form> %>

      <%= form_with(url:"/todos", method: "post", class: "AddTodo" ) do |form| %>
        <%= form.text_field :todo_text,
          class: "AddTodo__Text",
          value: "Whats Next?",
          autofocus: "autofocus"
        %>
        <%= form.date_field :due_date,
          class: "AddTodo__Date"
        %>
        <%= submit_tag "Add", class: "AddTodo__Button" %>
      <% end %>

      <%= render partial: "todo-section", locals: {
        section_title: "Overdue",
        todos: @todos.overdue,
        show_duedate: true
        }
      %>
      <%= render partial: "todo-section", locals: {
        section_title: "Due Today",
        todos: @todos.duetoday,
        show_duedate: false
        }
      %>
      <%= render partial: "todo-section", locals: {
        section_title: "Due Later",
        todos: @todos.duelater,
        show_duedate: true
        }
      %>

    </article>
  </main>

app/views/user/new.html.erb
<div class="Users__addmain">

  <section class="Users__new">
    <p class="Users__title"> Welcome to new user </p>
    <%= form_with url: users_path do |form| %>
      <div class="Form__section">
        <p class="FormInput__label" > First name: </p>
        <%= form.text_field :first_name,
          class: "Form__input",
          autofocus: "autofocus"
        %>
      </div>
      <div class="Form__section">
        <p class="FormInput__label" > Last name: </p>
        <%= form.text_field :last_name, class: "Form__input" %>
      </div>
      <div class="Form__section">
        <p class="FormInput__label" > Email id: </p>
        <%= form.email_field :email, class: "Form__input" %>
      </div>
      <div class="Form__section">
        <p class="FormInput__label" >Password: </p>
        <%= form.password_field :password, class: "Form__input" %>
      </div>
      <div class="Form__section">
        <%= form.submit "Sign-up!", class: "Form__submit" %>
      <div>
    <% end %>
  </section>

</div>